---
title: C28198
ms.date: 11/04/2016
ms.technology: vs-ide-code-analysis
ms.topic: reference
f1_keywords:
- C28198
helpviewer_keywords:
- C28198
ms.assetid: 8bad4acb-712c-43f5-81d1-45d92092d4c5
author: mikeblome
ms.author: mblome
manager: wpickett
ms.workload:
- multiple
ms.openlocfilehash: fd02eece9197fd42c12bfcb558c041dfe1dff464
ms.sourcegitcommit: 42ea834b446ac65c679fa1043f853bea5f1c9c95
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 04/19/2018
---
# <a name="c28198"></a>C28198
警告 C28198: 例外によりメモリがリークしている可能性があります

 この警告は、割り当てられたメモリを解放されていない例外が発生した後を示します。 パスの最後に、ステートメントは、例外を生成できます。 メモリは、後で解放されるコピーが保存した関数に渡されました。

 この警告は警告によく似た[C28197](../code-quality/c28197.md)です。 警告で使用するために推奨される注釈[C28197](../code-quality/c28197.md)ここでも使用できます。

## <a name="example"></a>例
 次のコード例では、この警告が生成されます。

```
char *p1 = new char[10];
char *p2 = new char[10];

test(p1);   // does not save a copy of p

delete[] p2;
delete[] p1;
```

 次のコード例では、この警告は生成されません。

```
char *p1 = new char[10];
char *p2 = NULL;

test(p1);   // does not save a copy of p
try {
    p2 = new char[10];
} catch (std::bad_alloc *e) {
    // just handle the throw
    ;
}
```